"""add foreignkey to product table and create manufacturer table

Revision ID: 1dea55d72d45
Revises: 6536a5b1ffc9
Create Date: 2024-08-28 13:26:22.297783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dea55d72d45'
down_revision: Union[str, None] = '6536a5b1ffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.add_column('products', sa.Column('manufacturer_id', sa.Integer(), nullable=False))
    op.create_foreign_key('products_manufacturers_fk', 'products', 'manufacturers', ['manufacturer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_manufacturers_fk', 'products', type_='foreignkey')
    op.drop_column('products', 'manufacturer_id')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
